spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: XXXXXXXXXXXXXXXX
      secret-key: olYzngfk2r3oE69f1fcjVn9artzNtW
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: mail-ssc

  application:
    name: mail-third-party
server:
  port: 30000
